S4/Group8/Group8/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^pros/', include('pros.urls')),
    url(r'^admin/', admin.site.urls),
]

S4/Group8/pros/urls.py
from django.conf.urls import url

from . import views


app_name = 'pros'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cadastro_ordem/$', views.cadastro_ordem, name='cadastro_ordem'),
    url(r'^update_ordem/(?P<pk>[0-9]+)/$', views.update_ordem, name='update_ordem'),
    url(r'^delete_ordem/(?P<pk>[0-9]+)$', views.delete_ordem, name='delete_ordem'),
    url(r'^empresas/$', views.empresas, name='empresas'),
    url(r'^empresas/delete_empresa/(\d+)/$', views.delete_empresa, name='delete_empresa'),
    url(r'^empresas/(?P<empresa_id>[0-9]+)/$', views.clientes, name='clientes'),
    url(r'^empresas/cadastro_empresa/$', views.cadastro_empresa, name='cadastro_empresa'),
    url(r'^empresas/update_empresa/(\d+)/$', views.update_empresa, name='update_empresa'),
    url(r'^empresas/(?P<empresa_id>[0-9]+)/cadastro_cliente/$', views.cadastro_cliente, name='cadastro_cliente'),
    url(r'^empresas/(?P<empresa_id>[0-9]+)/update_cliente/(?P<pk>[0-9]+)/$', views.update_cliente, name='update_cliente'),
    url(r'^empresas/(?P<empresa_id>[0-9]+)/delete_cliente/(?P<pk>[0-9]+)/$', views.delete_cliente, name='delete_cliente'),
]


S4/Group8/pros/models.py
from django.db import models
from datetime import datetime


class Empresa(models.Model):
    
    nome_empresa = models.CharField(max_length=200)
    nome_social = models.CharField(max_length=200)
    cnpj = models.CharField(max_length=20, unique=True)
    insc_estadual = models.CharField(max_length=20)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    end = models.CharField(max_length=300)
    cep = models.CharField(max_length=10)

    def __str__(self):
        return self.nome_empresa


class Cliente(models.Model):
    
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    solicitante = models.CharField(max_length=100)
    responsavel = models.CharField(max_length=100)
    cargo = models.CharField(max_length=100, blank=True)
    tel = models.CharField(max_length=50)
    ramal = models.CharField(max_length=50)
    cel = models.CharField(max_length=50)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.responsavel


class Ordem(models.Model):

    # O id está implícito na criação da tabela e será usado como número da ordem serviço;
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    data = models.DateField(default=datetime.now(), blank=True)
    num_nf_entrada = models.CharField(max_length=20)
    descricao = models.CharField(max_length=512)
    acessorios = models.CharField(max_length=200)
    observacoes = models.CharField(max_length=200)
    data_envio_orcamento = models.CharField(max_length=12)
    data_aprovacao = models.CharField(max_length=12)
    num_pedido = models.CharField(max_length=100)
    valor = models.IntegerField()
    executante = models.CharField(max_length=100)
    data_liberacao = models.CharField(max_length=12)
    num_nf_servico = models.CharField(max_length=20)
    num_nf_vendas = models.CharField(max_length=20)
    num_nf_devolucao = models.CharField(max_length=20)
    responsavel_preenchimento = models.CharField(max_length=100)

    def __str__(self):
        return self.id

S4/Group8/pros/forms.py
import datetime
from localflavor.br.forms import BRCNPJField, BRPhoneNumberField, STATE_CHOICES
from django import forms
from .models import Empresa, Cliente, Ordem


class CadastrarEmpresa(forms.ModelForm):
	
	nome_empresa = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'nome_empresa'}))
	nome_social = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'nome_social'}))
	cnpj = BRCNPJField(max_length=18, min_length=14, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'cnpj'}))
	insc_estadual = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'insc_estadual'}))
	cidade = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'cidade'}))
	estado = forms.ChoiceField(choices=STATE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
	end = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'end'}))
	cep = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'cep'}))

	class Meta:
		model = Empresa
		fields = ('nome_empresa', 'nome_social', 'cnpj', 'insc_estadual', 'cidade', 'estado', 'end', 'cep')


class CadastrarCliente(forms.ModelForm):
	
	solicitante = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'solicitante'}))
	responsavel = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'responsavel'}))
	cargo = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'cargo'}))
	tel = BRPhoneNumberField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'tel'}))
	ramal = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'ramal'}))
	cel = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'cel'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'email', 'type': 'email'}))

	class Meta:
		model = Cliente
		fields = ('solicitante', 'responsavel', 'cargo', 'tel', 'ramal', 'cel', 'email')


class CadastrarOrdem(forms.ModelForm):
	
	#id = num_pedido
	cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), widget=forms.Select(attrs={'class': 'cliente'}))
	data = forms.DateField()
	data_envio = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'data_envio'}))
	data_aprovado = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'data_aprovado'}))
	descricao = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'descricao'}))
	acessorios = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'acessorios'}))
	observacoes = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'observacoes'}))
	num_pedido = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'num_pedido'}))
	valor = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'valor'}))
	executante = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'executante'}))
	data_liberacao = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'data_liberacao'}))
	num_nf_entrada = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'num_nf_entrada'}))
	num_nf_servico = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'num_nf_servico'}))
	num_nf_vendas = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'num_nf_vendas'}))
	num_nf_devolucao = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'num_nf_devolucao'}))
	responsavel_preenchimento = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'responsavel_preenchimento'}))

	class Meta:
		model = Ordem
		exclude = ('data',)
		fields = ('cliente', 'num_nf_entrada', 'descricao', 'acessorios', 'observacoes', 'data_envio', 'data_aprovado',
				  'num_pedido', 'valor', 'executante', 'data_liberacao', 'num_nf_servico', 'num_nf_vendas',
				  'num_nf_devolucao', 'responsavel_preenchimento')

S4/Group8/pros/views.py
from datetime import date
from django.shortcuts import render, redirect
from .models import Cliente, Empresa, Ordem
from .forms import CadastrarEmpresa, CadastrarCliente, CadastrarOrdem


def index(request):
    ordem_list = Ordem.objects.order_by('data')
    return render(request, 'pros/index.html', {'ordem_list': ordem_list})

# Empresas:-------------------------------------------------------------------------------------------


def empresas(request):
    empresa_list = Empresa.objects.order_by('nome_empresa')
    return render(request, 'pros/empresas.html', {'empresa_list': empresa_list})


def cadastro_empresa(request):
    if request.method == 'POST':
        form = CadastrarEmpresa(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pros:empresas')
    else:
        form = CadastrarEmpresa()
    return render(request, 'pros/cadastro_empresa.html', {'form': form})


def update_empresa(request, pk):
    empresa = Empresa.objects.get(pk=pk)
    form = CadastrarEmpresa(request.POST or None, instance=empresa)
    if form.is_valid():
        form.save()
        return redirect('pros:empresas')
    return render(request, 'pros/update_empresa.html', {'form': form, 'pk': pk})



def delete_empresa(request, pk):
    Empresa.objects.filter(id=pk).delete()
    return redirect('pros:empresas')

# Clientes:--------------------------------------------------------------------------------------------


def clientes(request, empresa_id):
    client_list = Cliente.objects.filter(empresa_id=empresa_id)
    nome_empresa = Empresa.objects.filter(id=empresa_id).get().nome_empresa
    return render(request, 'pros/clientes.html', {'client_list': client_list, 'nome_empresa': nome_empresa,
                                                    'empresa_id': empresa_id})


def cadastro_cliente(request, empresa_id):

    empresa_fk = Empresa.objects.get(id=empresa_id)

    if request.method == 'POST':
        form = CadastrarCliente(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.empresa = empresa_fk
            form.save()
            return redirect('pros:clientes', empresa_id)
        else:
            return redirect('pros:clientes', empresa_id)
    else:
        form = CadastrarCliente()
        nome_empresa = Empresa.objects.filter(id=empresa_id).get().nome_empresa
    return render(request, 'pros/cadastro_cliente.html', {'form': form, 'empresa_id': empresa_id,
                                                             'nome_empresa': nome_empresa})


def delete_cliente(request, empresa_id, pk):
    Cliente.objects.filter(id=pk).delete()
    return redirect('pros:clientes', empresa_id)


def update_cliente(request, empresa_id, pk):
    cliente = Cliente.objects.get(pk=pk)
    form = CadastrarCliente(request.POST or None, instance=cliente)

    if form.is_valid():
        form.save()
        return redirect('pros:clientes', empresa_id)
    nome_empresa = Empresa.objects.filter(id=empresa_id).get().nome_empresa
    return render(request, 'pros/update_cliente.html', {'form': form, 'empresa_id': empresa_id,
                                                             'nome_empresa': nome_empresa, 'pk': pk})


# Ordens:----------------------------------------------------------------------------------------------
def ordem(request):
    ordem_list = Ordem.objects.order_by('id')
    return render(request, 'pros/index.html', {'ordem_list': ordem_list})


def cadastro_ordem(request):
    empresa_list = Empresa.objects.all
    client_list = Cliente.objects.all

    if request.method == 'POST':
        form = CadastrarOrdem(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('pros:index')
    else:
        form = CadastrarOrdem()
    return render(request, 'pros/cadastro_ordem.html', {'form': form, 'client_list': client_list,
                                                        'empresa_list': empresa_list})


def update_ordem(request, pk):
    up_ordem = Ordem.objects.get(pk=pk)
    form = CadastrarEmpresa(request.POST or None, instance=up_ordem)
    if form.is_valid():
        form.save()
        return redirect('pros:index')
    return render(request, 'pros/update_ordem.html', {'form': form, 'pk': pk})


def delete_ordem(request, pk):
    Ordem.objects.filter(id=pk).delete()
    return redirect('pros:index')

S4/Group8/pros/templates/pros/cadastro_cliente.html
<!DOCTYPE HTML>

{% load staticfiles %}

<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>RSA</title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/pros.css' %}">

        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script src="{% static 'js/pros.js' %}"></script>

    </head>
    <body>
        <header class="page-header text-center color-link-cliente">
            <h1><strong>RSA</strong> - Ordem de serviço</h1>
        </header>
        <div class="container">
            <ul class="breadcrumb">
                <li><a class="color-link-cliente" href="{% url 'pros:index' %}">Orçamentos</a><span class="divider"></span></li>
                <li><a class="color-link-cliente" href="{% url 'pros:empresas' %}">Empresas</a> <span class="divider"></span></li>
                <li>
                    <a class="color-link-cliente" href="{% url 'pros:clientes' empresa_id=empresa_id %}"> {{ nome_empresa }} </a>
                    <span class="divider"></span>
                </li>
                <li class="active">Cadastro de Empresa</li>
            </ul>
            <form action="{% url 'pros:cadastro_cliente' empresa_id=empresa_id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group col">
                            <label for="solicitante">Nome do Solicitante:</label>
                            {{ form.solicitante }}
                        </div>
                    </div>
                     <div class="col-sm-6">
                        <div class="form-group col">
                            <label for="responsavel">Nome do Responsável:</label>
                            {{ form.responsavel }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group col">
                            <label for="cargo">Cargo do Cliente:</label>
                            {{ form.cargo }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="tel">Telefone:</label>
                            {{ form.tel }}
                        </div>
                    </div>
                      <div class="col-sm-1">
                        <div class="form-group">
                            <label for="ramal">Ramal:</label>
                            {{ form.ramal }}
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="cel">Celular:</label>
                            {{ form.cel }}
                        </div>
                    </div>
                    <div class="col-sm-4">
                         <div class="form-group">
                            <label for="email">E-mail:</label>
                            {{ form.email }}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Cadastrar</button>
                <a href="{% url 'pros:clientes' empresa_id=empresa_id %}" type="reset" class="btn btn-danger">Cancelar</a>
            </form>
        </div>
    </body>
</html>

S4/Group8/pros/templates/pros/cadastro_empresa.html
<!DOCTYPE HTML>

{% load staticfiles %}

<html lang="pt-br">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>RSA</title>
		
    <!--CSS--------------------------------------------------------------------------------------------------------------->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/pros.css' %}">
    <!-------------------------------------------------------------------------------------------------------------------->
		
	</head>
	<body>
		<!-- Quando houver erros no forms: -->
		{% if form.errors %}
		<div class="alert alert-danger alert-dismissable fade-in">
			<a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<strong>Erro!</strong> O cadastro da empresa falhou! Reveja o seu CNPJ!
		</div>
		{% endif %}
		<!-- Fim do erro no forms -->
		<header class="page-header text-center color-link-empresa">
			<h1><strong>RSA</strong> - Ordem de serviço</h1>
		</header>
		<div class="container">
			<ul class="breadcrumb">
				<li><a class="color-link-empresa" href="{% url 'pros:index' %}">Orçamentos</a><span class="divider"></span></li>
				<li><a class="color-link-empresa" href="{% url 'pros:empresas' %}">Empresas</a> <span class="divider"></span></li>
				<li class="active">Cadastro de Empresa</li>
			</ul>
			<form action="{% url 'pros:cadastro_empresa' %}" method="post">
				{% csrf_token %}
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group col">
							<label for="nome_empresa">Nome Empresa:</label>
							{{ form.nome_empresa }}
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group col">
							<label for="nome_social">Razão Social:</label>
							{{ form.nome_social }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-3">
						<div class="form-group">
							<label for="cnpj">CNPJ:</label>
							{{ form.cnpj }}
						</div>
					</div>
					<div class="col-sm-3">
						 <div class="form-group">
							<label for="insc_estadual">Inscrição Estatual:</label>
							{{ form.insc_estadual }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-4">
						<div class="form-group">
							<label for="cidade">Cidade:</label>
							{{ form.cidade }}
						</div>
					</div>
					<div class="col-sm-3">
						 <div class="form-group">
							<label for="estado">Estado:</label>
							{{ form.estado }}
						</div>
					</div>
					<div class="col-sm-3">
						<div class="form-group">
							<label for="cep">CEP:</label>
							{{ form.cep }}
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="end">Endereço:</label>
					{{ form.end }}
				</div>
				<button type="submit" class="btn btn-success">Cadastrar</button>
				<a href="{% url 'pros:empresas' %}" type="reset" class="btn btn-danger">Cancelar</a>
			</form>
		</div>
		
	    <!--JAVASCRIPT-------------------------------------------------------------------------------------------------------->
	    <script async  src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	    <script async  src="{% static 'js/jquery.mask.min.js' %}"></script>
	    <script async  src="{% static 'js/bootstrap.min.js' %}"></script>
	    <script async  src="{% static 'js/bootstrap-table.min.js' %}"></script>
	    <script async  src="{% static 'js/bootstrap-table-pt-BR.min.js' %}"></script>
	    <script async  src="{% static 'js/pros.js' %}"></script>
	    <!-------------------------------------------------------------------------------------------------------------------->
	</body>
</html>

S4/Group8/pros/templates/pros/empresas.html
<!DOCTYPE HTML>

{% load staticfiles %}

<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>RSA</title>

<!--CSS--------------------------------------------------------------------------------------------------------------->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/pros.css' %}">
<!-------------------------------------------------------------------------------------------------------------------->

    </head>
    <body>
        <header class="page-header text-center color-link-empresa">
            <h1><strong>RSA</strong> - Ordem de serviço</h1>
        </header>
        <div class="container">
            <ul class="breadcrumb">
                <li><a class="color-link-empresa" href="{% url 'pros:index' %}">Orçamentos</a>
                    <span class="divider"></span></li>
                <li class="active">Empresas</li>
            </ul>
            <div id="toolbar-empresa">
                <a type="button" class="btn btn-success" href="{% url 'pros:cadastro_empresa' %}">
                    <i class="glyphicon glyphicon-log-in"></i> Cadastrar Empresa
                </a>
            </div>
            <table data-toggle="table"
                data-toolbar="#toolbar-empresa"
                data-search="true"
                data-sort-name="nome_empresa"
                data-sort-order="desc"
                data-pagination="true"
                data-show-footer="false"
                data-page-list="[10, 25, 50, 100, ALL]"
                data-minimum-count-columns="2"
                data-show-columns="true">
                <thead>
                    <tr>
                        <th data-field="nome_empresa" data-sortable="true">Empresa</th>
                        <th data-field="cnpj" data-sortable="true">CNPJ</th>
                        <th data-field="cidade" data-sortable="true">Cidade</th>
                        <th data-field="insc_estadual" data-sortable="true">Inscrição Estadual</th>
                        <th data-field="nome_social" data-sortable="true">Nome Social</th>
                        <th data-field="estado" data-sortable="true">Estado</th>
                        <th data-field="end" data-sortable="true">Endereço</th>
                        <th data-field="cep" data-sortable="true">CEP</th>
                        <th data-field="action" class="col-md-1" data-align="center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empresa in empresa_list %}
                        <tr>
                            <td class="text-overflow">
                                <a class="color-link-empresa" href="{% url 'pros:clientes' empresa.id %}">
                                    {{ empresa.nome_empresa }}
                                </a>
                            </td>
                            <td class="text-overflow">{{ empresa.cnpj }}</td>
                            <td class="text-overflow">{{ empresa.cidade }}</td>
                            <td class="text-overflow">{{ empresa.insc_estadual }}</td>
                            <td class="text-overflow">{{ empresa.nome_social }}</td>
                            <td class="text-overflow">{{ empresa.estado }}</td>
                            <td class="text-overflow">{{ empresa.end }}</td>
                            <td class="text-overflow">{{ empresa.cep }}</td>
                            <td class="col-md-1" data-align="center">
                                <a class="edit ml10" href="{% url 'pros:update_empresa' empresa.id %}" title="Edit">
                                    <i class="glyphicon glyphicon-edit color-link-empresa"></i>
                                </a>
                                <a class="remove ml10 remove-empresa" title="Remove" data-toggle="modal" href="#"
                                   data-id="{{ empresa.id }}" data-name="{{ empresa.nome_empresa }}"
                                   data-target="#empresa-del">
                                    <i class="glyphicon glyphicon-remove color-delete"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="modal fade" id="empresa-del" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header modal-header-del">
                            <h4 class="modal-title">Alerta</h4>
                        </div>
                        <div class="modal-body">

                        </div>
                        <div class="modal-footer">
                            <a type="button" class="btn btn-success btn-yes">Sim</a>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--JAVASCRIPT-------------------------------------------------------------------------------------------------------->
        <script async  src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script async  src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script async  src="{% static 'js/bootstrap.min.js' %}"></script>
        <script async  src="{% static 'js/bootstrap-table.min.js' %}"></script>
        <script async  src="{% static 'js/bootstrap-table-pt-BR.min.js' %}"></script>
        <script async  src="{% static 'js/pros.js' %}"></script>
        <!-------------------------------------------------------------------------------------------------------------------->
    </body>
</html>

S4/Group8/pros/templates/pros/index.html
<!DOCTYPE HTML>

{% load staticfiles %}

<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>RSA</title>
<!--CSS--------------------------------------------------------------------------------------------------------------->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/pros.css' %}">
<!-------------------------------------------------------------------------------------------------------------------->
<!--JAVASCRIPT-------------------------------------------------------------------------------------------------------->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-table.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-table-pt-BR.min.js' %}"></script>
        <script src="{% static 'js/pros.js' %}"></script>
<!-------------------------------------------------------------------------------------------------------------------->
    </head>
    <body>
        <header class="page-header text-center color-link-orcamento">
            <h1><strong>RSA</strong> - Ordem de serviço</h1>
        </header>
        <div class="container">
            <ul class="breadcrumb">
                <li class="active">Orçamento</li>
            </ul>
            <div id="toolbar-orcamento">
                <a type="button" class="btn btn-primary" href="{% url 'pros:cadastro_ordem' %}">
                    <i class="glyphicon glyphicon-log-in"></i> Criar Orçamento
                </a>
                <a type="button" class="btn btn-success" href="{% url 'pros:empresas' %}">
                    <i></i> Empresas
                </a>
            </div>
            <div id="toolbar-empresa">

            </div>
            <table data-toggle="table"
                data-toolbar="#toolbar-orcamento"
                data-toolbar="#toolbar-empresa"
                data-search="true"
                data-sort-name="nome_empresa"
                data-sort-order="desc"
                data-pagination="true"
                data-show-footer="false"
                data-page-list="[10, 25, 50, 100, ALL]"
                data-minimum-count-columns="2"
                data-show-columns="true">
                <thead>
                    <tr>
                        <th data-field="num_ordem" data-sortable="true">ID</th>
                        <th data-field="data" data-sortable="true">Data</th>
                        <th data-field="executante" data-sortable="true">Executante</th>
                        <th data-field="estado" data-sortable="true">Situação</th>
                        <th data-field="action" class="col-md-1" data-align="center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ordem in ordem_list %}
                        <tr>
                            <td class="text-overflow">{{ ordem.id }}</td>
                            <td class="text-overflow">{{ ordem.data }}</td>
                            <td class="text-overflow">{{ ordem.executante }}</td>
                           <!--- <td class="text-overflow">{{ ordem.estado }}</td> --->
                            <td class="col-md-1" data-align="center">
                                <a class="edit ml10" href="update_ordem/{{ ordem.id }}" title="Edit">
                                    <i class="glyphicon glyphicon-edit color-link-empresa"></i>
                                </a>
                                <a class="remove ml10 delete_ordem" title="Remove" data-toggle="modal" href="#"
                                   data-id="{{ ordem.id }}"
                                   data-target="#client-del">
                                    <i class="glyphicon glyphicon-remove color-delete"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>